const fs = require('fs');

// Read the file
const content = fs.readFileSync('lib/i18n.ts', 'utf8');

// Define all replacements
const replacements = [
  // Handle triple-encoded first (most specific)
  ['Configuracií³n', 'Configuración'],
  ['Electrí³nico', 'Electrónico'],
  ['Compilacií³n', 'Compilación'],
  ['prí³ximas', 'próximas'],
  ['Contraseí±a', 'Contraseña'],
  ['Prí³ximamente', 'Próximamente'],
  ['afectarí¡n', 'afectarán'],
  ['Enví­a', 'Envía'],
  ['Misií³n', 'Misión'],
  ['diseí±ada', 'diseñada'],
  ['funcií³n', 'función'],
  ['Tecnolí³gico', 'Tecnológico'],
  ['Conéctate', 'Conéctate'],
  ['Descripción', 'Descripción'],
  ['Reunión', 'Reunión'],
  ['Título', 'Título'],
  ['Duración', 'Duración'],
  ['Próximas', 'Próximas'],
  ['Planificación', 'Planificación'],
  ['Tecnologías', 'Tecnologías'],
  ['Última', 'Última'],
  ['actualización', 'actualización'],
  ['Categoría', 'Categoría'],
  ['Discusión', 'Discusión'],
  ['Conexión', 'Conexión'],
  ['Decisión', 'Decisión'],
  ['Investigación', 'Investigación'],
  ['resúmenes', 'resúmenes'],
  ['Artículo', 'Artículo'],
  ['artículos', 'artículos'],
  ['Solución', 'Solución'],
  
  // Then handle double-encoded
  ['ó³n', 'ón'],
  ['í³n', 'ión'],
  ['ó³', 'ó'],
  ['í³', 'ió'],
  ['ó±a', 'ña'],
  ['í±a', 'ña'],
  ['ó±', 'ñ'],
  ['í±', 'ñ'],
  ['ó­a', 'ía'],
  ['í­a', 'ía'],
  ['ó­', 'í'],
  ['í­', 'í'],
  ['ó¡', 'á'],
  ['í¡', 'á'],
  ['ó©', 'é'],
  ['í©', 'é'],
  ['óº', 'ú'],
  ['íº', 'ú'],
  ['ó¨', 'è'],
  ['í¨', 'è'],
  ['ó ', 'à'],
  ['í ', 'à'],
  ['ó§', 'ç'],
  ['í§', 'ç'],
  ['ó´', 'ô'],
  ['í´', 'ô'],
  ['ó¹', 'ù'],
  ['í¹', 'ù'],
  ['ó¼', 'ü'],
  ['í¼', 'ü'],
  ['ó¶', 'ö'],
  ['í¶', 'ö'],
  ['ó¤', 'ä'],
  ['í¤', 'ä'],
  ['óŸ', 'ß'],
  ['íŸ', 'ß'],
  ['óš', 'Ú'],
  ['íš', 'Ú'],
  ['ó‰', 'É'],
  ['í‰', 'É'],
  ['ó‹', 'Ë'],
  ['í‹', 'Ë'],
  
  // Then handle original mojibake
  ['Ã³', 'ó'],
  ['Ã±', 'ñ'],
  ['Ã­', 'í'],
  ['Ã¡', 'á'],
  ['Ã©', 'é'],
  ['Ãº', 'ú'],
  ['Ã¨', 'è'],
  ['Ã ', 'à'],
  ['Ã§', 'ç'],
  ['Ã', 'ê'],
  ['Ã´', 'ô'],
  ['Ã¹', 'ù'],
  ['Ã¼', 'ü'],
  ['Ã¶', 'ö'],
  ['Ã¤', 'ä'],
  ['ÃŸ', 'ß'],
  ['Ã‰', 'É'],
  ['Ãš', 'Ú'],
  ['Ã‹', 'Ë'],
  ['Â¿', '¿'],
  ['Â¡', '¡'],
  
  // French characters
  ['CommunautÃ©', 'Communauté'],
  ['ParamÃ¨tres', 'Paramètres'],
  ['DÃ©connecter', 'Déconnecter'],
  ['TÃ¢ches', 'Tâches'],
  ['Tí¢ches', 'Tâches'],
  ['déjí ', 'déjà'],
  ['Réunions', 'Réunions'],
  ['Créer', 'Créer'],
  ['í¢', 'â'],
  ['í ', 'à'],
  ['í©', 'é'],
  ['í¨', 'è'],
  ['í´', 'ô'],
  ['í»', 'û'],
  ['Ã¢', 'â'],
  ['Ã®', 'î'],
  ['Ã¯', 'ï'],
  ['Ã´', 'ô'],
  ['Ã»', 'û'],
  ['Ã§', 'ç'],
  ['Ã‡', 'Ç'],
  ['Ã€', 'À'],
  ['Ã‚', 'Â'],
  ['Ã‰', 'É'],
  ['Ãˆ', 'È'],
  ['Ãª', 'ê'],
  ['Ã‹', 'Ë'],
  ['Ã®', 'î'],
  ['Ã', 'Î'],
  ['Ã"', 'Ô'],
  ['Ã›', 'Û'],
];

let fixed = content;
for (const [old, newChar] of replacements) {
  fixed = fixed.split(old).join(newChar);
}

// Write back
fs.writeFileSync('lib/i18n.ts', fixed, 'utf8');

console.log('Successfully fixed all encoding issues!');
